apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.bluemix.net/sticky-cookie-services: "serviceName=frontend name=sticky expires=5h path=/ hash=sha1"
    ingress.bluemix.net/client-max-body-size: "size=10m"
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
  - hosts:
    - cloud.annotations.ai
    secretName: certbot-annotations-secret
  - hosts: 
    - annotations2-442dbba0442be6c8c50f31ed96b00601-0000.us-east.containers.appdomain.cloud
    secretName: annotations2-442dbba0442be6c8c50f31ed96b00601-0000
  rules:
  - host: cloud.annotations.ai
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 443
      - path: /docs
        backend:
          serviceName: docs
          servicePort: 80
      - path: /workshops
        backend:
          serviceName: docs
          servicePort: 80
      - path: /demos
        backend:
          serviceName: docs
          servicePort: 80
      - path: /sdks
        backend:
          serviceName: docs
          servicePort: 80
      - path: /docs-assets
        backend:
          serviceName: docs
          servicePort: 80

  - host: annotations2-442dbba0442be6c8c50f31ed96b00601-0000.us-east.containers.appdomain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 443
      - path: /docs
        backend:
          serviceName: docs
          servicePort: 80
      - path: /workshops
        backend:
          serviceName: docs
          servicePort: 80
      - path: /demos
        backend:
          serviceName: docs
          servicePort: 80
      - path: /sdks
        backend:
          serviceName: docs
          servicePort: 80
      - path: /docs-assets
        backend:
          serviceName: docs
          servicePort: 80