apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
    # ingress.bluemix.net/sticky-cookie-services: "serviceName=frontend name=sticky expires=5h path=/ hash=sha1"
    # ingress.bluemix.net/client-max-body-size: "size=10m"
    # ingress.bluemix.net/redirect-to-https: "True"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
  - hosts:
    - test.cloud.annotations.ai
    - cloud.annotations.ai
    secretName: certbot-annotations-secret
  - hosts: 
    - cloud-annotations-442dbba0442be6c8c50f31ed96b00601-0000.us-east.containers.appdomain.cloud
    secretName: cloud-annotations-442dbba0442be6c8c50f31ed96b00601-0000
  rules:
  - host: cloud.annotations.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 443
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /workshops
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /demos
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /sdks
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /docs-assets
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80

  - host: test.cloud.annotations.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 443
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /workshops
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /demos
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /sdks
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /docs-assets
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80

  - host: cloud-annotations-442dbba0442be6c8c50f31ed96b00601-0000.us-east.containers.appdomain.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 443
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /workshops
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /demos
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /sdks
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
      - path: /docs-assets
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
