name: Deployment

concurrency: production

on:
  push:
    branches:
      - master

env:
  DEPLOY_TO: production
  CLUSTER_ID: c6bbmpjw0i2st0vc9gr0
  IMAGE_NAME: us.icr.io/cloud-annotations/frontend:${{ github.sha }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "*"
      - name: Install IBM Cloud CLI
        run: curl -sL https://ibm.biz/idt-installer | bash
      - name: Deploy
        run: ./deploy.sh